_common_env: &_common_env
  SRC_DIR: /tmp/source
  DEST_DIR: /tmp/dest
  BACKUP_INTERVAL: 0
  EXCLUDES: '*.jar,exclude_dir'
  RCON_PATH: /usr/bin/rcon-cli
  DEBUG: true

services:
  - docker

jobs:
  include:
    - stage: Linting and sanity tests
      name: Lint script with shellcheck
      script: ./tests/lint.shellcheck.sh
    - name: Lint dockerfile
      script: bash ./tests/lint.hadolint.sh
    - name: Test simple backup and exclusion scenario with tar
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y
          tree
          coreutils
      env:
        <<: *_common_env
        EXTRACT_DIR: /tmp/extract
        INITIAL_DELAY: 5s
        PRUNE_BACKUPS_DAYS: 3
      script: bash ./tests/test.simple.tar.sh
    - name: Test restic handling
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y
          tree
          coreutils
      env:
        <<: *_common_env
        RESTIC_REPOSITORY: /tmp/dest
        INITIAL_DELAY: 0s
        RESTIC_PASSWORD: 1234
      script: bash ./tests/test.simple.restic.sh
    - name: Test restic rclone handling
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y
          tree
          coreutils
      env:
        <<: *_common_env
        RESTIC_REPOSITORY: rclone:/tmp/dest
        INITIAL_DELAY: 0s
        RESTIC_PASSWORD: 1234
      script: bash ./tests/test.simple.restic.sh
